services:
  database:
    container_name: ads-poo-ecommerce-database
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
