spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    generate-ddl: true
    defer-datasource-initialization: true
